#Properties for LiteLoader 1.8.0
#Wed Apr 17 21:58:01 BRT 2024
forceInjection=false
soundManagerFix=true
tabAlwaysExpanded=false
search.jarfiles=true
version.macrokeybindmod=32
search.mods=true
log=stderr
allowForceUpdate=false
loadingbar=true
search.classpath=true
modInfoScreen=true
search.jar=false
disableJInput=false
